# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM ghcr.io/astral-sh/uv:alpine

# Set working directory
WORKDIR /app

# Copy project files
COPY . /app

# Install dependencies using uv
RUN uv sync

# Expose required ports (none, using stdio)
# Default command
CMD ["uv", "--directory", "/app", "run", "server.py"]
